language: d

sudo: required
dist: bionic

d:
  - dmd
  - ldc

os:
  - linux
  - osx

script:
  - dub test --compiler=${DC}
  - dub test --compiler=${DC} :core
  - dub build --compiler=${DC} -b plain
  - dub build --compiler=${DC} -b plain :core
  - dub build --compiler=${DC} -b release
  - dub build --compiler=${DC} -b release :core
  - dub fetch ddox
  - test ! -e ~/.dub/packages/ddox-0.16.13 || sed -i 's/^import std.conv;/public \0/' "$HOME/.dub/packages/ddox-0.16.13/ddox/source/ddox/api.d"
  - test ! ${DC} = dmd -a ! ${TRAVIS_OS_NAME} = linux || dub build --compiler=${DC} -b ddox

before_deploy:
  - cp -rv .circleci docs/

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    condition:
      - ${DC} = dmd
      - ${TRAVIS_OS_NAME} = linux
  cache:
    directories:
      - $HOME/.dub
  verbose: true
