language: d

sudo: required
dist: bionic

branches:
  except:
    - /appveyor-.*/
    - /circleci-.*/
    - gh-pages

d:
  - dmd
  - ldc

os:
  - linux
  - osx

script:
  - dub test  --compiler=${DC}
  - dub build --compiler=${DC} -b debug
  - dub build --compiler=${DC} -b plain
  - dub build --compiler=${DC} -b release

before_deploy:
  - dub build --compiler=${DC} -b ddox
  - cp -rv .circleci docs/

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch:
      - master
      - /travis-.*/
    condition:
      - ${DC} = dmd
      - ${TRAVIS_OS_NAME} = linux
  cache:
    directories:
      - $HOME/.dub
  verbose: true
