language: d

sudo: required
dist: bionic

branches:
  except:
    - /appveyor-.*/
    - /circleci-.*/
    - gh-pages

d:
  - dmd
  - ldc

os:
  - linux
  - osx

script:
  - echo "${TRAVIS_OS_NAME}"
  - uname
  - dub test --compiler=${DC}
  - dub test --compiler=${DC} :core
  - dub build --compiler=${DC} -b plain
  - dub build --compiler=${DC} -b plain :core
  - dub build --compiler=${DC} -b release
  - dub build --compiler=${DC} -b release :core
  - dub fetch ddox
  - test "${DC}" = dmd -a "$(uname)" = "Linux" || return 0
  - test ! -e "$HOME/.dub/packages/ddox-0.16.13" || sed -i "s/import std.conv;/public import std.conv;/" "$HOME/.dub/packages/ddox-0.16.13/ddox/source/ddox/api.d"
  - dub build --compiler=${DC} -b ddox

before_deploy:
  - cp -rv .circleci docs/

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    condition:
      - ${DC} = dmd
      - ${TRAVIS_OS_NAME} = linux
  cache:
    directories:
      - $HOME/.dub
  verbose: true
