language: d

sudo: required
dist: focal

branches:
  except:
    - /appveyor-.*/
    - /circleci-.*/
    - gh-pages
    - /dustmite-.*/

d:
  - dmd
  - ldc

os:
  - linux
  - osx

script:
  - time dub test  --compiler=${DC}
  - time dub build --compiler=${DC} -b debug
  - time dub build --compiler=${DC} -b plain
  - time dub build --compiler=${DC} -b release

before_deploy:
  #- time dub build --compiler=${DC} --nodeps --force -b ddox
  - dub fetch adrdox
  - dub run adrdox -- -ip --header-title="lu" --directory docs source
  - cp -rv .circleci docs/

deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN
  on:
    branch:
      - master
      - /travis-.*/
    condition:
      - ${DC} = dmd
      - ${TRAVIS_OS_NAME} = linux
  cache:
    directories:
      - $HOME/.dub
  verbose: true
