language: d

sudo: required
dist: focal

branches:
  except:
    - /appveyor-.*/
    - /circleci-.*/
    - gh-pages
    - /dustmite-.*/
    - /github-.*/

d:
  - dmd
  - ldc

os:
  - linux
  - osx

script:
  - time dub test  --compiler=${DC}
  - time dub build --compiler=${DC} -b debug
  - time dub build --compiler=${DC} -b plain
  - time dub build --compiler=${DC} -b release
