platform: x64

environment:
  matrix:
    - DC: dmd
      #DVersion: latest
      arch: x64
    - DC: dmd
      DVersion: 2.108.0
      arch: x64
    - DC: ldc
      #DVersion: latest
      arch: x64
    - DC: ldc
      DVersion: 1.38.0
      arch: x64

branches:
  except:
    - /circleci-.*/
    - /travis-.*/
    - gh-pages
    - /dustmite-.*/
    - /github-.*/

install:
  - ps: function SetUpDCompiler
        {
          mkdir "$env:USERPROFILE\dlang" -Force;
          Invoke-WebRequest "https://dlang.org/install.sh" -OutFile "$env:USERPROFILE\dlang\install.sh";
          pushd;
          cd "$env:USERPROFILE\dlang";
          if (Test-Path env:DVersion) {
            & bash install.sh install $env:DC-$env:DVersion;
            $env:activator = & bash install.sh install $env:DC-$env:DVersion -a;
          }
          else {
            & bash install.sh install $env:DC;
            $env:activator = & bash install.sh install $env:DC -a;
          }
          popd;
        }
  - ps: SetUpDCompiler
  - "%activator%"

before_build:
  - ps: $env:toolchain = "msvc";
  - ps: if ($env:arch -eq "x86") {
          $env:compilersetupargs = "x86";
          $env:Darch = "x86";
          $env:DConf = "m32";
        }
        elseif ($env:arch -eq "x64") {
          $env:compilersetupargs = "amd64";
          $env:Darch = "x86_64";
          $env:DConf = "m64";
        }
  - ps: if ($env:DC -eq "ldc") {
          $env:DC = "ldc2";
        }
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'

build_script:
 - echo dummy build script - dont remove me

test_script:
 - echo %DC% on %PLATFORM% (%Darch%)
 - '%DC% --version'
 - dub --version
 - dub test  --arch=%Darch% --compiler=%DC% %dubArgs%
 - dub build --arch=%Darch% --compiler=%DC% %dubArgs% -b debug
 - dub build --arch=%Darch% --compiler=%DC% %dubArgs% -b plain
 - dub build --arch=%Darch% --compiler=%DC% %dubArgs% -b release
